export const LOGIN_START = 'LOGIN_START';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGIN_RESET = 'LOGIN_RESET';
export const LOGOUT = 'LOGOUT';

export const USERS_FOLLOWING_START = 'USERS_FOLLOWING_START';
export const USERS_FOLLOWING_SUCCESS = 'USERS_FOLLOWING_SUCCESS';
export const USERS_FOLLOWING_ERROR = 'USERS_FOLLOWING_ERROR';

export const TIMELINE_LOADING_START = 'TIMELINE_LOADING_START';
export const TIMELINE_LOADING_SUCCESS = 'TIMELINE_LOADING_SUCCESS';
export const TIMELINE_LOADING_ERROR = 'TIMELINE_LOADING_ERROR';
